
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_READLINE = 57;
  public static final int T_OPADMIRACION = 37;
  public static final int T_DOUBLE = 5;
  public static final int T_WHILE = 15;
  public static final int T_OPRESTAN = 61;
  public static final int T_EXTENDS = 12;
  public static final int T_OPPARENTESISDER = 45;
  public static final int T_ELSE = 17;
  public static final int T_OPSUMA = 23;
  public static final int T_OPCORCHETES = 50;
  public static final int T_INT = 4;
  public static final int T_PRINT = 55;
  public static final int T_OPCOMA = 39;
  public static final int T_COMENTARIOS = 22;
  public static final int T_FOR = 14;
  public static final int T_ENTER = 51;
  public static final int T_OPBRACKETDER = 43;
  public static final int T_RETURN = 18;
  public static final int T_OPBRACKETS = 48;
  public static final int T_NEWARRAY = 21;
  public static final int T_OPDIFERENTE = 34;
  public static final int T_INT1 = 67;
  public static final int T_OPPUNTOCOMA = 38;
  public static final int T_READINTEGER = 56;
  public static final int T_STRINGA = 68;
  public static final int T_WHITE = 52;
  public static final int T_CORCHETES = 63;
  public static final int T_OPDOBLEIGUAL = 33;
  public static final int T_OPCORCHETEIZQ = 46;
  public static final int T_OPPUNTO = 41;
  public static final int T_COMENTARIOS2 = 53;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int T_OPPARENTESIS = 49;
  public static final int T_NEW = 20;
  public static final int T_OPMAYORQUE = 30;
  public static final int T_CONSTBOOL = 66;
  public static final int T_OPPORCENTAJE = 27;
  public static final int T_OPMULTI = 25;
  public static final int T_IGUAL = 32;
  public static final int T_INTERFACE = 9;
  public static final int T_CLASS = 8;
  public static final int ERROR = 40;
  public static final int T_OPPARENTESISIZQ = 44;
  public static final int T_GETBYTE = 59;
  public static final int T_STRING = 7;
  public static final int T_ENTERODECIMAL = 64;
  public static final int T_MALLOC = 58;
  public static final int T_SETBYTE = 60;
  public static final int T_ERRORCOMENTARIOS = 54;
  public static final int T_OPMENORIGUAL = 29;
  public static final int T_IMPLEMENTS = 13;
  public static final int T_BOOL = 6;
  public static final int T_DOUBLENUM = 69;
  public static final int T_OPAND = 35;
  public static final int T_THIS = 11;
  public static final int T_OPMAYORIGUAL = 31;
  public static final int T_OPCORCHETEDER = 47;
  public static final int T_BREAK = 19;
  public static final int T_OPDIV = 26;
  public static final int T_OPBRACKETIZQ = 42;
  public static final int T_OPOR = 36;
  public static final int T_ERROR = 62;
  public static final int T_OPMENORQUE = 28;
  public static final int T_OPRESTA = 24;
  public static final int T_ENTEROHEX = 65;
  public static final int T_IF = 16;
  public static final int T_NULL = 10;
  public static final int T_VOID = 3;
  public static final int T_IDENTIFICADOR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_IDENTIFICADOR",
  "T_VOID",
  "T_INT",
  "T_DOUBLE",
  "T_BOOL",
  "T_STRING",
  "T_CLASS",
  "T_INTERFACE",
  "T_NULL",
  "T_THIS",
  "T_EXTENDS",
  "T_IMPLEMENTS",
  "T_FOR",
  "T_WHILE",
  "T_IF",
  "T_ELSE",
  "T_RETURN",
  "T_BREAK",
  "T_NEW",
  "T_NEWARRAY",
  "T_COMENTARIOS",
  "T_OPSUMA",
  "T_OPRESTA",
  "T_OPMULTI",
  "T_OPDIV",
  "T_OPPORCENTAJE",
  "T_OPMENORQUE",
  "T_OPMENORIGUAL",
  "T_OPMAYORQUE",
  "T_OPMAYORIGUAL",
  "T_IGUAL",
  "T_OPDOBLEIGUAL",
  "T_OPDIFERENTE",
  "T_OPAND",
  "T_OPOR",
  "T_OPADMIRACION",
  "T_OPPUNTOCOMA",
  "T_OPCOMA",
  "ERROR",
  "T_OPPUNTO",
  "T_OPBRACKETIZQ",
  "T_OPBRACKETDER",
  "T_OPPARENTESISIZQ",
  "T_OPPARENTESISDER",
  "T_OPCORCHETEIZQ",
  "T_OPCORCHETEDER",
  "T_OPBRACKETS",
  "T_OPPARENTESIS",
  "T_OPCORCHETES",
  "T_ENTER",
  "T_WHITE",
  "T_COMENTARIOS2",
  "T_ERRORCOMENTARIOS",
  "T_PRINT",
  "T_READINTEGER",
  "T_READLINE",
  "T_MALLOC",
  "T_GETBYTE",
  "T_SETBYTE",
  "T_OPRESTAN",
  "T_ERROR",
  "T_CORCHETES",
  "T_ENTERODECIMAL",
  "T_ENTEROHEX",
  "T_CONSTBOOL",
  "T_INT1",
  "T_STRINGA",
  "T_DOUBLENUM"
  };
}

