
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 22 07:41:49 CST 2018
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETES = 59;
  public static final int READLINE = 32;
  public static final int PUNTOYCOMA = 50;
  public static final int ENTERO = 63;
  public static final int DIFERENTE = 46;
  public static final int RESTA = 36;
  public static final int DOUBLE = 12;
  public static final int PARENTESIS = 60;
  public static final int PARENIZQ = 55;
  public static final int SEMI = 2;
  public static final int LLAVEDER = 58;
  public static final int PORCENTAJE = 39;
  public static final int INTERFACE = 16;
  public static final int INT = 11;
  public static final int FOR = 21;
  public static final int IDENTIFICADOR = 62;
  public static final int AND = 47;
  public static final int MENORIGUAL = 41;
  public static final int CORCHIZQ = 53;
  public static final int IGUAL = 44;
  public static final int READINTEGER = 30;
  public static final int OR = 48;
  public static final int IGUALDAD = 45;
  public static final int BOOL = 13;
  public static final int CONSTBOOLEANAS = 9;
  public static final int CLASS = 15;
  public static final int SUMA = 35;
  public static final int NEWARRAY = 28;
  public static final int IF = 23;
  public static final int THIS = 18;
  public static final int GETBYTE = 33;
  public static final int CONSTSTRING = 8;
  public static final int MAYORIGUAL = 43;
  public static final int SETBYTE = 34;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int COMA = 51;
  public static final int OP_MULT = 5;
  public static final int NEGACION = 49;
  public static final int MENOR = 40;
  public static final int NULL = 17;
  public static final int OP_RESTA = 4;
  public static final int PARENDER = 56;
  public static final int BREAK = 26;
  public static final int VOID = 10;
  public static final int MAYOR = 42;
  public static final int ELSE = 24;
  public static final int PUNTO = 52;
  public static final int CORCHDER = 54;
  public static final int LLAVES = 61;
  public static final int WHILE = 22;
  public static final int LLAVEIZQ = 57;
  public static final int CONSTENTERO = 7;
  public static final int CONSTDOUBLE = 6;
  public static final int EXTENDS = 19;
  public static final int STRING = 14;
  public static final int MALLOC = 31;
  public static final int OP_SUMA = 3;
  public static final int DIVISION = 38;
  public static final int IMPLEMENTS = 20;
  public static final int PRINT = 29;
  public static final int MULTIPLICACION = 37;
}

