/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package analizador;

/**
 *
 * @author Carlos
 */
public enum Token {
    T_IDENTIFICADOR, T_VOID, T_INT, T_DOUBLE, T_BOOL, T_STRING, T_CLASS, T_INTERFACE,
    T_NULL, T_THIS, T_EXTENDS, T_IMPLEMENTS, T_FOR, T_WHILE, T_IF, T_ELSE, T_RETURN, T_BREAK, T_NEW,
    T_NEWARRAY, T_ENTERODECIMAL, T_ENTEROHEX, T_CONSTBOOL, T_INT1, T_STRINGA,
    T_COMENTARIOS,T_OPSUMA, T_OPRESTA, T_OPMULTI, T_OPDIV, T_OPPERCENTAJE, T_OPMENORQUE,
    T_OPMENORIGUAL, T_OPMAYORQUE, T_OPMAYORIGUAL, T_IGUAL, T_OPDOBLEIGUAL, T_OPDIFERENTE,
    T_OPAND, T_OPOR, T_OPADMIRACION, T_OPPUNTOCOMA, T_OPCOMA, T_OPPORCENTAJE, ERROR, T_OPPUNTO,
    T_OPBRACKETIZQ, T_OPBRACKETDER, T_OPPARENTESISIZQ, T_OPPARENTESISDER, T_OPCORCHETEIZQ, T_OPCORCHETEDER,
    T_OPBRACKETS, T_OPPARENTESIS, T_OPCORCHETES, T_ENTER, T_WHITE, T_DOUBLENUM, T_COMENTARIOS2, T_ERRORCOMENTARIOS
    
    
}
